version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  demo_threatrix: theatrix/demo_threatrix@dev:alpha

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

filters: &filters
  tags:
    only: /.*/

# Filter for release tags.
release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows: # a single workflow with a single job called build
  test-deploy:
    jobs:
      - demo_threatrix/install_and_scan_code:
          oid: ${threatrix_oid}
          eid: threatrix_eid
          api_key: threatrix_api_key
          dir: ./
          filters: *filters
          context: threatrix
          - run: # print the name of the branch we're on
              name: "What branch am I on?"
              command: echo ${CIRCLE_BRANCH}
      # The orb must be re-packed for publishing, and saved to the workspace.
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: theatrix/demo_threatrix
          vcs_type: << pipeline.project.type >>
          pub_type: production
          # Ensure this job requires all test jobs and the pack job.
          requires:
            - orb-tools/pack
            - demo_threatrix/install_and_scan_code
          context: orb-publishing
          filters: *release-filters