version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  demo_threatrix: theatrix/demo_threatrix@dev:alpha

references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

# jobs:
#   threatrix_scan:
#     docker:
#       - image: circleci/openjdk:11-jdk-node
#     working_directory: ~/repo
#     environment:
#       MAVEN_OPTS: -Xmx3200m
#     steps:
#       - *attach_workspace
#       - checkout
#       - demo_threatrix/install_and_scan_code:
#       - run: # print the name of the branch we're on
#           name: "What branch am I on?"
#           command: echo ${$threatrix_oid} 
            

          # context: threatrix
          # oid: $threatrix_oid
          # eid: $threatrix_eid
          # api_key: $threatrix_api_key
          # dir: ./
          

workflows: # a single workflow with a single job called build
  test-deploy:
    jobs:
      - demo_threatrix/install_and_scan_code:
          oid: threatrix_oid
          eid: threatrix_eid
          api_key: threatrix_api_key
          dir: ./
          context: threatrix

