description: >
  Java image for threatrix
docker:
  - image: circleci/openjdk:<< parameters.tag >>
parameters:
  tag:
    default: "11-jdk-node"
    description: >
      Circleci java image
    type: string
